### ISSUE TITLE
Compiling edge in travis-ci

### ISSUE THREAD

**Issue by crisfervil** [tjanczuk/edge#406]
Hi,

I'm trying to build my project (https://github.com/crisfervil/DynamicsNode) using travis-ci, but unfortunatelly I'm having problems when installing edge in this enviroment.

The error I'm getting is this (seen in the travis-ci log  https://travis-ci.org/crisfervil/DynamicsNode/builds/116357373 )

Error: The edge native module is not available at /home/travis/build/crisfervil/DynamicsNode/node_modules/edge/build/Release/edge_coreclr.node. You can use EDGE_NATIVE environment variable to provide alternate location of edge.node. If you need to build edge.node, follow build instructions for your platform at https://github.com/tjanczuk/edge

I've seen that edge itself is being built using travis-ci, so I've tried to copy the .travis.yml configuration and I've added this to my project .travis.yml
(https://github.com/crisfervil/DynamicsNode/blob/master/.travis.yml)

```
install:
 - sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
 - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy main' >> /etc/apt/sources.list.d/mono-xamarin.list"
 - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main' >> /etc/apt/sources.list.d/mono-xamarin.list"
 - sudo apt-get update
 - sudo apt-get install mono-devel
 - npm install -g grunt-cli
 - npm install
```

Having a closer look to the log, I see this error when performing the edge install:
```
> edge@5.0.0 install /home/travis/build/crisfervil/DynamicsNode/node_modules/edge
> node tools/install.js
make: Entering directory `/home/travis/build/crisfervil/DynamicsNode/node_modules/edge/build'
  CXX(target) Release/obj.target/edge_nativeclr/src/mono/clractioncontext.o
cc1plus: error: unrecognized command line option ‘-std=c++11’
make: *** [Release/obj.target/edge_nativeclr/src/mono/clractioncontext.o] Error 1
make: Leaving directory `/home/travis/build/crisfervil/DynamicsNode/node_modules/edge/build'
```

Apparently, edge is not being built correctly.

May be the version of node be the cause? Should I use an older version? I'm currently trying to build it on the latest stable version: 5.8.0

Any Ideas?

Thanks!

**Comment by tjanczuk** [comment]
Have you tried using node 0.12? Although I don't see how a node version would have anything to do with a lack of a C++ compiler option.

**Comment by crisfervil** [comment]
I've just tried and It doesn't work either. Here's the full log: https://travis-ci.org/crisfervil/DynamicsNode/jobs/116425412

Still the same problem with the c++ compiler option.

One thing I'm curious about is, why is trying to get the coreclr native module, if only Mono is installed in the travis-ci image?

![image](https://cloud.githubusercontent.com/assets/7902357/13821084/0aac0fc4-eb98-11e5-9b75-c45d56cc7e2a.png)

**Comment by crisfervil** [comment]
After a few tests, I think the problem is related to the g++ version. 
http://stackoverflow.com/questions/27341599/cc1plus-error-unrecognized-command-line-option-std-c11

So, following the travis-ci documentation, I've specified the g++ version I want to use
https://docs.travis-ci.com/user/languages/cpp/#stq=&stp=0


The .travis.yml looks like this now:
```
language: node_js

node_js:
  - "node"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - sudo apt-key adv --keyserver pgp.mit.edu --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy main' >> /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo sh -c "echo 'deb http://download.mono-project.com/repo/debian wheezy-libtiff-compat main' >> /etc/apt/sources.list.d/mono-xamarin.list"
  - sudo apt-get update
  - sudo apt-get install mono-devel
  - npm install -g grunt-cli
  - npm install
 
before_script: npm run build
```

And now it works like a charm!!
